<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container037EUjH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container037EUjH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container037EUjH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container037EUjH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container037EUjH\App_KernelDevDebugContainer([
    'container.build_hash' => '037EUjH',
    'container.build_id' => '69b506dc',
    'container.build_time' => 1755427961,
], __DIR__.\DIRECTORY_SEPARATOR.'Container037EUjH');
